# Generated by Django 5.1.1 on 2024-09-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "uid",
                    models.IntegerField(
                        default=1, primary_key=True, serialize=False, verbose_name="UID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("edited", models.DateTimeField(auto_now=True)),
                (
                    "session_uid",
                    models.IntegerField(default=1, verbose_name="Session UID"),
                ),
                (
                    "player",
                    models.CharField(
                        choices=[("Randy", "Randy"), ("Cooper", "Cooper")],
                        default="Randy",
                        max_length=40,
                        verbose_name="Player",
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[("2", "Two"), ("3", "Three"), ("4", "Four")],
                        default="4",
                        max_length=1,
                        verbose_name="Game Type",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("1", "First"),
                            ("2", "Second"),
                            ("3", "Third"),
                            ("4", "Fourth"),
                        ],
                        default="1",
                        max_length=1,
                        verbose_name="Place",
                    ),
                ),
                (
                    "map_choice",
                    models.CharField(
                        choices=[
                            ("Banshee Boardwalk", "Bb"),
                            ("Bowser's Castle", "Bc"),
                            ("Choco Mountain", "Cm"),
                            ("D.K.'s Jungle", "Dkj"),
                            ("Frappe Snowland", "Fs"),
                            ("Kalimari Desert", "Kd"),
                            ("Koopa Troopa Beach", "Ktb"),
                            ("Luigi Raceway", "Lr"),
                            ("Mario Raceway", "Mr"),
                            ("Moo Moo Farm", "Mmf"),
                            ("Royal Raceway", "Rr"),
                            ("Sherbert Land", "Sl"),
                            ("Toad's Turnpike", "Tt"),
                            ("Wario Stadium", "Ws"),
                            ("Yoshi Valley", "Yv"),
                        ],
                        default="Banshee Boardwalk",
                        max_length=20,
                        verbose_name="Map",
                    ),
                ),
                ("season", models.SmallIntegerField(default=0, verbose_name="Season")),
            ],
        ),
    ]
