# Generated by Django 5.1.1 on 2024-09-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mk_form", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="place",
        ),
        migrations.RemoveField(
            model_name="data",
            name="player",
        ),
        migrations.AddField(
            model_name="data",
            name="new_session",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=3,
                verbose_name="New Session",
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="player_first",
            field=models.CharField(
                choices=[("Randy", "Randy"), ("Cooper", "Cooper")],
                default="Randy",
                max_length=40,
                verbose_name="Player",
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="player_fourth",
            field=models.CharField(
                choices=[("Randy", "Randy"), ("Cooper", "Cooper")],
                default="Randy",
                max_length=40,
                verbose_name="Player",
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="player_second",
            field=models.CharField(
                choices=[("Randy", "Randy"), ("Cooper", "Cooper")],
                default="Randy",
                max_length=40,
                verbose_name="Player",
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="player_third",
            field=models.CharField(
                choices=[("Randy", "Randy"), ("Cooper", "Cooper")],
                default="Randy",
                max_length=40,
                verbose_name="Player",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="map_choice",
            field=models.CharField(
                choices=[
                    ("Banshee Boardwalk", "Banshee Boardwalk"),
                    ("Bowser's Castle", "Bowser's Castle"),
                    ("Choco Mountain", "Choco Mountain"),
                    ("D.K.'s Jungle", "D.K.'s Jungle"),
                    ("Frappe Snowland", "Frappe Snowland"),
                    ("Kalimari Desert", "Kalimari Desert"),
                    ("Koopa Troopa Beach", "Koopa Troopa Beach"),
                    ("Luigi Raceway", "Luigi Raceway"),
                    ("Mario Raceway", "Mario Raceway"),
                    ("Moo Moo Farm", "Moo Moo Farm"),
                    ("Royal Raceway", "Royal Raceway"),
                    ("Sherbert Land", "Sherbert Land"),
                    ("Toad's Turnpike", "Toad's Turnpike"),
                    ("Wario Stadium", "Wario Stadium"),
                    ("Yoshi Valley", "Yoshi Valley"),
                ],
                default="Banshee Boardwalk",
                max_length=20,
                verbose_name="Map",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="uid",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="UID",
            ),
        ),
    ]
