# Generated by Django 5.1.1 on 2024-09-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mk_form", "0002_remove_data_place_remove_data_player_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="player_first",
            field=models.CharField(
                choices=[("Randy", "Randy"), ("Cooper", "Cooper")],
                default="Randy",
                max_length=40,
                verbose_name="Player (1st)",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="player_fourth",
            field=models.CharField(
                choices=[("Randy", "Randy"), ("Cooper", "Cooper")],
                default="Randy",
                max_length=40,
                verbose_name="Player (4th)",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="player_second",
            field=models.CharField(
                choices=[("Randy", "Randy"), ("Cooper", "Cooper")],
                default="Randy",
                max_length=40,
                verbose_name="Player (2nd)",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="player_third",
            field=models.CharField(
                choices=[("Randy", "Randy"), ("Cooper", "Cooper")],
                default="Randy",
                max_length=40,
                verbose_name="Player (3rd)",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="uid",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UID",
            ),
        ),
    ]
