# Generated by Django 5.1.1 on 2024-09-25 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mk_form", "0003_alter_data_player_first_alter_data_player_fourth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="custom_date",
            field=models.DateField(
                default=datetime.datetime(2024, 9, 25, 16, 18, 56, 387820),
                verbose_name="Some Date",
            ),
        ),
    ]
