# Generated by Django 5.1.1 on 2024-09-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mk_form", "0005_player_remove_data_custom_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
    ]
