# Generated by Django 5.1.1 on 2024-09-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mk_form", "0006_alter_player_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=20, null=True, unique=True
            ),
        ),
    ]
