# Generated by Django 5.1.1 on 2024-09-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mk_form", "0008_alter_player_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="new_session",
        ),
        migrations.RemoveField(
            model_name="data",
            name="season",
        ),
        migrations.RemoveField(
            model_name="data",
            name="session_uid",
        ),
        migrations.RemoveField(
            model_name="data",
            name="uid",
        ),
        migrations.AddField(
            model_name="data",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
