# Generated by Django 5.1.1 on 2024-10-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mk_form", "0009_remove_data_new_session_remove_data_season_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="character_first",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Peach", "Peach"),
                    ("Yoshi", "Yoshi"),
                    ("Toad", "Toad"),
                    ("Bowser", "Bowser"),
                    ("Luigi", "Luigi"),
                    ("Mario", "Mario"),
                    ("Wario", "Wario"),
                    ("D.K.", "D.K."),
                ],
                max_length=6,
                null=True,
                verbose_name="Character (1st)",
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="character_fourth",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Peach", "Peach"),
                    ("Yoshi", "Yoshi"),
                    ("Toad", "Toad"),
                    ("Bowser", "Bowser"),
                    ("Luigi", "Luigi"),
                    ("Mario", "Mario"),
                    ("Wario", "Wario"),
                    ("D.K.", "D.K."),
                ],
                max_length=6,
                null=True,
                verbose_name="Character (4th)",
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="character_second",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Peach", "Peach"),
                    ("Yoshi", "Yoshi"),
                    ("Toad", "Toad"),
                    ("Bowser", "Bowser"),
                    ("Luigi", "Luigi"),
                    ("Mario", "Mario"),
                    ("Wario", "Wario"),
                    ("D.K.", "D.K."),
                ],
                max_length=6,
                null=True,
                verbose_name="Character (2nd)",
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="character_third",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Peach", "Peach"),
                    ("Yoshi", "Yoshi"),
                    ("Toad", "Toad"),
                    ("Bowser", "Bowser"),
                    ("Luigi", "Luigi"),
                    ("Mario", "Mario"),
                    ("Wario", "Wario"),
                    ("D.K.", "D.K."),
                ],
                max_length=6,
                null=True,
                verbose_name="Character (3rd)",
            ),
        ),
    ]
